services:
  telemt:
    image: whn0thacked/telemt-docker:3.3.28
    container_name: telemt
    restart: unless-stopped
    user: "root"
    environment:
      RUST_LOG: "info"
    command: ["/etc/telemt/telemt.toml"]
    volumes:
      - ./telemt:/etc/telemt/:rw
    security_opt:
      - no-new-privileges:true
    ports:
      - "${INTERNAL_IP}:443:443/tcp"
      - "${INTERNAL_IP}:9090:9090"
      - "${INTERNAL_IP}:9091:9091"
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    tmpfs:
      - /tmp:rw,nosuid,nodev,noexec,size=16m
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
    depends_on:
      - api
    networks:
      - telemt-network
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"

  api:
    build: .
    container_name: telemt-api
    ports:
      - "${INTERNAL_IP}:8000:8000"
    volumes:
     - ./telemt/telemt.toml:/app/telemt/telemt.toml
      - ./src:/app/src/
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - telemt-network
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  telemt-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}/16
