show_link = ["*"]

[[upstreams]]
type = "direct"
enabled = true
weight = 10

[general]
prefer_ipv6 = false
fast_mode = true
use_middle_proxy = false

[server]
port = 443
listen_addr_ipv4 = "0.0.0.0"
listen_addr_ipv6 = "::"

[censorship]
tls_domain = "petrovich.ru"
mask = true
mask_port = 443
fake_cert_len = 2048

[general.modes]
classic = false
secure = false
tls = true

[access.users]

