---
mtproto_repo_url: https://github.com/youngwishes/my-mtproto-vds-instance.git
mtproto_deploy_dir: /opt/mtproto
mtproto_repo_branch: main
mtproto_swap_size_mb: 2048
telemt_version: 3.4.25
telemt_release_base_url: https://github.com/telemt/telemt/releases/download
telemt_binary_path: /usr/local/bin/telemt
telemt_config_path: "{{ mtproto_deploy_dir }}/telemt/telemt.toml"
telemt_work_dir: /opt/telemt
telemt_download_dir: "/var/cache/telemt/{{ telemt_version }}"
telemt_service_name: telemt
telemt_api_root: http://host.docker.internal:9091/v1
telemt_release_arches:
  x86_64: x86_64
  aarch64: aarch64
telemt_archive_name: "telemt-{{ telemt_release_arch }}-linux-musl.tar.gz"
telemt_caddy_dependency: false
mtproto_zapret2_version: "1.0.3"
mtproto_zapret2_archive_name: "zapret2-v{{ mtproto_zapret2_version }}.tar.gz"
mtproto_zapret2_release_url: >-
  https://github.com/bol-van/zapret2/releases/download/v{{ mtproto_zapret2_version }}/{{ mtproto_zapret2_archive_name }}
mtproto_zapret2_archive_sha256: 5220d9253b1fc858c7a1e0a6340f2d87f2e30ed24f71c5cee19dfc458734e6a5
mtproto_zapret2_download_dir: "/var/cache/zapret2/{{ mtproto_zapret2_version }}"
mtproto_zapret2_extract_dir: >-
  {{ mtproto_zapret2_download_dir }}/zapret2-v{{ mtproto_zapret2_version }}
mtproto_zapret2_arches:
  x86_64: linux-x86_64
  aarch64: linux-arm64
mtproto_zapret2_install_dir: /opt/zapret2
mtproto_zapret2_binary_path: /opt/zapret2/bin/nfqws2
mtproto_zapret2_lua_dir: /opt/zapret2/lua
mtproto_zapret2_config_path: /etc/zapret2/mtproto.conf
mtproto_zapret2_start_script_path: /usr/local/sbin/mtpr-zapret2-start.sh
mtproto_zapret2_service_name: mtpr-zapret2
mtproto_zapret2_ready_script_path: /usr/local/sbin/mtpr-zapret2-ready.sh
mtproto_zapret2_nft_binary: /usr/sbin/nft
mtproto_zapret2_iptables_binary: /usr/sbin/iptables
mtproto_zapret2_table: MTProto
mtproto_zapret2_port: 443
mtproto_zapret2_queue_num: 200
mtproto_zapret2_fwmark: "0x40000000"
mtproto_zapret2_conntrack_mark: "0x00040000"
mtproto_zapret2_combined_mark: "0x40040000"
mtproto_zapret2_split_length: 400
mtproto_zapret2_synack_window: 1400
mtproto_zapret2_ack_window: 10
