---
- name: Restart MTProto Zapret2
  ansible.builtin.systemd_service:
    name: "{{ mtproto_zapret2_service_name }}.service"
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart Telemt
  ansible.builtin.systemd_service:
    name: "{{ telemt_service_name }}"
    state: restarted
    enabled: true
    daemon_reload: true
