---
- name: Restart Caddy
  ansible.builtin.systemd_service:
    name: caddy.service
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart Telemt
  ansible.builtin.systemd_service:
    name: "{{ telemt_service_name }}"
    state: restarted
    enabled: true
    daemon_reload: true
