[mtproto_servers]
vds1 ansible_host=5.253.188.65
vds2 ansible_host=82.47.169.229
vds3 ansible_host=91.124.19.3
vds4 ansible_host=144.31.159.47

[mtproto_servers:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_ed25519_deploy
