[mtproto_servers]
vds1 ansible_host=82.47.169.229
vds2 ansible_host=91.124.19.3
vds3 ansible_host=144.31.159.47
vds4 ansible_host=166.88.225.36
vds5 ansible_host=5.180.21.84
vds6 ansible_host=31.76.31.138

[mtproto_servers:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_ed25519_deploy

[mtproto_dev]
vds6

[mtproto_prod]
vds1
vds2
vds3
vds4
vds5
