show_link = [ "application",]

[[upstreams]]
type = "direct"
enabled = true
weight = 1

[general]
fast_mode = true
use_middle_proxy = true

[network]
ipv4 = true
ipv6 = false
prefer = 4

[server]
port = 443
listen_addr_ipv4 = "0.0.0.0"
listen_addr_ipv6 = "::"

[server.api]
enabled = true
listen = "0.0.0.0:9091"
whitelist = []
read_only = false

[censorship]
tls_domain = "beatvault.ru"
mask = true
mask_port = 443
fake_cert_len = 2048
tls_emulation = true

[general.modes]
classic = false
secure = false
tls = true

[access.users]
application = "f7500d69d0479eb1c90454490aa7096d"

[access.user_max_unique_ips]
application = 1